### PR TITLE
Add OFFSET

### PR DESCRIPTION
**Pull request by gijsaddas**
Introduces OFFSET argument when using the LIMIT function

### CODE REVIEW

**Comment by J0** [comment]
Hey! 

Wanted to check in on the PR - is the `setup.py` file needed? Otherwise it seems fine to me - might want to consider merging in the Sorcery refactoring

**Comment by deleted** [comment]
Hey, this seems like a pretty useful addition to the API. Just wanted to check in on what the status of merging it. (Looks to me like the setup.py could be removed completely since a `pyproject.toml` exists).

If you came here just looking for a way to do pagination, be advised that a `range()` method also exists on the query builder, though beware that it decrements its `end` parameter before emitting the header for some reason: https://github.com/supabase-community/postgrest-py/blob/29e91a2123d1363963c1ba50c87fce38f0bef263/postgrest_py/base_request_builder.py#L366

**Comment by J0** [comment]
@deleted I'll make the changes and merge it if there's no update by end of day UTC. I do sometimes lose track though - so feel free to bump if I don't get back by then.

**Comment by J0** [comment]
Merged in via #326 

thanks for the contribution!

**Pull request closed without merging**
